version: "3"

services: 
    ftp:
        tty: true
        networks:
        - default
        ports:
        - 7822:22/tcp
        - 7821:21/tcp
        build:
            context: .
            dockerfile: Dockerfile
