version: "3"

services: 
    conventions:
        tty: true
        networks:
        - default
        ports:
        - 8622:22/tcp
        build:
            context: .
            dockerfile: Dockerfile
